name=SRJC_Robot_ARM
version=6.6.6
author=Antone Bajor
maintainer=Antone Bajor
sentence=PCA9685 16-channel 12-bit PWM controller.
paragraph=Plibt
category=Device Control
url=
architectures=Arduino and Linux
